### ISSUE TITLE
UI fun

### ISSUE THREAD

**Issue by alexcouper** [pretenders/ployst#81]
I think we may be getting rid of the left hand bar, but anyway, there's some weirdness going on when you scroll right with a smaller window:

![screen shot 2014-12-01 at 10 02 42 pm](https://cloud.githubusercontent.com/assets/837734/5254143/de68fbbc-79a5-11e4-91f4-81689002b8e4.png)

**Comment by txels** [comment]
:) I'll fix that in one of my next PRs.
