### ISSUE TITLE
Store all branches in DB

### ISSUE THREAD

**Issue by alexcouper** [pretenders/ployst#83]
Recalculate method only stores branches of interest based on features that are defined. This is not what we want. 

From @txels in #76: 

> The recalculate algorithm is based on the existance of features, but doesn't update any info on local branches if features are missing - I suggest we implemented that to close one loop: update local branch info with updated branch data coming from the hook

We should create/update branch data on every hook receipt.

**Comment by alexcouper** [comment]
In order to do this, I will be stripping out all notion of hierarchy and feature from the recalculate method.

Since recalculate lives in a module called "hierarchy", I think what I shall do is create a new method + module that the hook will currently use which is essentially to store the branch information so we can display and search based on it.

**Comment by txels** [comment]
Yes that is the way forward.
A new method `update_branch_info` or suchlike.
